name: Build-and-Release

on:
  workflow_dispatch:
  
env:
  solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release
  
jobs:
  OctoBuild:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.9
    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Testing
      run: dotnet test --no-restore --verbosity normal
      
      
      ##dotnet publish
    - name: Publish Web
      run: dotnet publish ${{ github.workspace }} --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}\output\
      
      
    #Pack files into zip
    - name: Package OctoDemo
      run: octo pack --id=${{ github.workspace }} --format=Zip --version=1.${{ github.run_number }}.0 --basePath=${{ github.workspace }}\output\ --outFolder=${{ github.workspace }}\output
      
    - name: Push OctoDemo
      run: octo push --package="${{ github.workspace }}\output"
      
      
      
      
  
  
