name: MyBuild

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest    
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/output"
    - name: Publish OctopusDemo
      run: dotnet publish OctopusDemo.ImageTextExtraction.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/"

    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.8
      with:
        version: latest
    - name: Package OctopusDemo
      run: |
        octo pack --id="OctopusDemo" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/" --outFolder="$GITHUB_WORKSPACE/output"

    - name: Push OctopusDemo packages
      uses: OctopusDeploy/push-package-action@v1.1.1
      with:
        api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
        server: ${{ secrets.OCTOPUSSERVERURL }}
        packages: "artifacts/*.${{ env.PACKAGE_VERSION }}.zip"



   
