name: Build-and-Release

on:
  workflow_dispatch:
  
env:
  solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release
  
jobs:
  OctoBuild:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
      
      ##dotnet publish
    - name: Publish Web
      run: dotnet publish ${{ github.workspace }} --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}\output\
    
